const sourceLink=(doc,label,detail)=>`<a class="source-card" href="originals.html?doc=${doc}" target="_blank" rel="noopener"><span class="source-icon">↗</span><span><b>${label}</b><small>${detail}</small></span><span class="source-arrow">查看原稿</span></a>`;

const caseData={
  vip:{
    label:'MEMBERSHIP EXPERIENCE / VIP FEATURE OPTIMIZATION',
    title:'VIP 功能专项重构',
    deck:'围绕“看懂权益—判断升级—领取奖励—完成充值”重组 VIP 体验，把会员信息从说明页变成可行动的产品路径。',
    meta:[['项目','VIP 功能页数据体验提升专项'],['工作重点','用户研究 / 体验策略 / 交互方案'],['原稿范围','总集第 3–19 页'],['结果','3 项转化指标均有提升']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / CONTEXT</p><h3>用户看得到 VIP，却不一定知道如何参与和升级。</h3><p>原方案指出，用户对 VIP 升级条件、权益内容和参与路径的理解有门槛；新用户容易卡在“是否加入、如何加入”，老用户则更关心每日领奖、当前特权和距离下一等级还有多远。权益说明与行动入口之间存在断点，信息越多不等于体验越清楚。</p><div class="case-callout"><span>PRODUCT GOAL</span><b>提升 VIP 权益使用率，同时让充值与投资转化路径更顺。</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / RESEARCH → DESIGN</p><h3>先围绕用户任务分层，再决定信息和入口的优先级。</h3><div class="logic-grid"><article><span>新用户</span><h4>先理解，再加入</h4><p>识别 VIP 价值与升级条件；需要明确等级规则和加入方式，避免读完说明仍不知道下一步。</p></article><article><span>活跃老用户</span><h4>先行动，再比较</h4><p>每日领取奖励、查看当前权益和升级差距是高频任务，入口需要直接、状态需要清楚。</p></article><article><span>对比型用户</span><h4>深入查看，按需展开</h4><p>需要完整等级权益、奖励构成和历史信息；低频细节放进可展开的详情层，避免主页面拥挤。</p></article></div><p>研究结论指出：除奖励比例外，用户更在意功能是否易用、规则是否容易理解；在产品早期，易用性是辅助用户做出决策的基础。</p></section>
      <section class="case-section"><p class="eyebrow">03 / USER FLOW</p><h3>新用户和老用户，从同一会员入口进入不同的高优先级任务。</h3><div class="flow-board"><div class="flow-row"><span>NEW MEMBER</span><div><b>VIP 入口</b><i>→</i><b>理解权益 / 条件</b><i>→</i><b>加入或升级</b><i>→</i><b>前往充值</b></div></div><div class="flow-row"><span>RETURNING</span><div><b>VIP 入口</b><i>→</i><b>查看当前等级</b><i>→</i><b>领取每日奖励</b></div></div><div class="flow-row"><span>COMPARE</span><div><b>当前权益</b><i>→</i><b>等级对比</b><i>→</i><b>奖励构成 / 明细</b></div></div></div></section>
      <section class="case-section"><p class="eyebrow">04 / INTERACTION DECISIONS</p><h3>缩短高频路径，低频信息保留深度。</h3><div class="decision-table"><div class="decision-head"><span>场景</span><span>交互处理</span><span>设计理由</span></div><div><b>首次了解 VIP</b><span>突出加入 / 充值主入口，减少跨页找路径</span><span>让理解能够直接接到转化动作</span></div><div><b>每日回访用户</b><span>把“领取奖励”作为清晰的快速动作</span><span>匹配高频任务，避免每次重新找入口</span></div><div><b>查看等级特权</b><span>分层展示权益与升级条件，支持展开查看</span><span>兼顾快速浏览和完整比较</span></div><div><b>查看奖励流水</b><span>展示来源、日期与构成明细</span><span>改善奖励透明度，帮助用户规划充值收益</span></div></div><div class="case-note">交互决策来自原项目页：重点区分新 / 老用户任务、权益详情层级及奖励构成明细。</div></section>
      <section class="case-section"><p class="eyebrow">05 / MEASURED RESULTS</p><h3>体验调整之后，权益使用、充值和投资转化都有提升。</h3><div class="before-after-grid"><article><span>VIP 使用率 · 领取奖励</span><div><b>3.28%</b><i>→</i><strong>17.01%</strong></div><small>+13.73 个百分点</small></article><article><span>充值转化率</span><div><b>11.74%</b><i>→</i><strong>12.98%</strong></div><small>+1.24 个百分点</small></article><article><span>投资转化率</span><div><b>13.62%</b><i>→</i><strong>16.73%</strong></div><small>+3.11 个百分点</small></article></div><div class="case-note">以上为原作品集“效果验证”页所列测前 / 测后数据。原页未标注样本量和测试时间窗口，故不补充统计口径。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL CASE / 17 PAGES</p><h3>打开 VIP 原版方案，逐页查看研究、路径与界面。</h3><p>原始章节单独成页打开，保留原版布局和截图；页面内可缩放、滚动，也可下载这 17 页对应章节。</p><div class="source-grid">${sourceLink('vip','VIP 功能页体验提升｜原版全稿','总集第 3–19 页 · 含测前测后数据')}</div></section>
      <div class="case-end"><span>MAXIN / CORE CASE 01</span><span>VIP EXPERIENCE / MEASURED OUTCOME</span></div>`
  },
  voc:{
    label:'VOC EXPERIENCE INSIGHT / VOICECHANGER',
    title:'海外个消软件 VOC 洞察分析报告',
    deck:'以 VOC 体验报告和竞品分析为起点，梳理语音产品的发现、选择和调节体验，将分散问题落到核心使用流程。',
    meta:[['项目','VOC 体验洞察 / VoiceChanger'],['工作方法','VOC 报告 / 竞品分析 / 优化方案'],['问题规模','23+ 项问题 · 4 条核心流程'],['结果','上线后日付费率环比 +49.63%']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / WHY THIS PROJECT</p><h3>声音内容很多，但用户不容易找到合适的声音并顺利用起来。</h3><p>原案例从 VOC 体验报告和竞品分析出发，检查实时变声主页面、声音分类、筛选、收藏与参数调节等关键触点。核心体验挑战集中在内容发现效率、分类理解和控制项辨识：入口层级混杂，用户需要额外翻找；相近的调节描述增加理解负担；Pro 标识和定制内容容易让用户把功能限制理解成付费诱导。</p></section>
      <section class="case-section"><p class="eyebrow">02 / VOC → EXPERIENCE FLOW</p><h3>把“找到声音”到“完成变声”的连续任务串起来。</h3><div class="journey"><div><i>01</i><b>进入实时变声</b><small>识别主要功能入口</small></div><div><i>02</i><b>浏览声音库</b><small>按主题 / 类型快速筛选</small></div><div><i>03</i><b>选择并预览</b><small>理解效果，减少反复试错</small></div><div><i>04</i><b>调整参数</b><small>区分可调项与当前状态</small></div><div><i>05</i><b>收藏 / 使用</b><small>方便回访常用声音</small></div><div><i>06</i><b>继续探索</b><small>明确免费与付费内容边界</small></div></div></section>
      <section class="case-section"><p class="eyebrow">03 / FROM FEEDBACK TO DESIGN</p><h3>用信息组织和状态表达，减少搜索与理解成本。</h3><div class="decision-table"><div class="decision-head"><span>观察到的阻力</span><span>方案方向</span><span>用户收益</span></div><div><b>分类与筛选入口层级混杂</b><span>重组声音分类与筛选层级，突出常用类别</span><span>更快找到目标内容，降低浏览成本</span></div><div><b>主页面内容多，付费内容不易感知</b><span>调整内容呈现顺序与 Banner 位置</span><span>提升内容发现效率，明确可用内容</span></div><div><b>参数描述相近，状态反馈不清</b><span>区分调节项、默认值和已变更状态</span><span>减少多余思考与误操作</span></div><div><b>收藏与近期使用内容难回找</b><span>补充收藏 / 最近使用的快捷入口</span><span>缩短重复使用流程</span></div></div><div class="case-note">以上方案点据原 VOC 案例第 20–37 页归纳；其中页面现有问题清单至少列出 17 项具体问题，完整原稿中有逐项标注。</div></section>
      <section class="case-section"><p class="eyebrow">04 / CORE FLOWS</p><h3>把 23+ 项体验问题，收敛到 4 条核心流程。</h3><div class="flow-board"><div class="flow-row"><span>DISCOVER</span><div><b>主功能入口</b><i>→</i><b>分类 / 筛选</b><i>→</i><b>声音内容</b></div></div><div class="flow-row"><span>PREVIEW</span><div><b>选择声音</b><i>→</i><b>预览效果</b><i>→</i><b>调整参数</b></div></div><div class="flow-row"><span>RETURN</span><div><b>收藏 / 最近使用</b><i>→</i><b>快速回到常用内容</b></div></div></div></section>
      <section class="case-section"><p class="eyebrow">05 / MEASURED RESULT</p><h3>上线后，日付费率环比提升 49.63%。</h3><div class="result-hero"><b>+49.63%</b><span>VoiceChanger 日付费率<br>上线后环比提升 · 简历记录</span></div><div class="case-note">该结果来自简历项目描述。现有材料没有提供样本量、统计窗口和基线值；因此这里只按原口径呈现，不扩写归因或因果。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL CASE / 18 PAGES</p><h3>查看 VOC 原版体验报告与优化方案。</h3><p>单独打开原作品集对应章节，包含问题分析、VOC / 竞品研究及方案页面；结果数字另由简历项目记录佐证。</p><div class="source-grid">${sourceLink('voc','VOC 体验洞察｜原版全稿','总集第 20–37 页 · VoiceChanger 体验案例')}${sourceLink('resume','马昕简历｜结果口径','完整简历 PDF · 日付费率提升记录')}</div></section>
      <div class="case-end"><span>MAXIN / CORE CASE 02</span><span>VOC INSIGHT / VOICECHANGER</span></div>`
  },
  cashback:{
    label:'BTCC / GROWTH EXPERIENCE / INDEPENDENT OWNER',
    title:'CEX 新用户孵化方案｜模拟返现',
    deck:'模拟返现不是一次性的活动页，而是把模拟体验、任务参与、奖励领取与真实交易连接起来的一段产品旅程。',
    meta:[['角色','独立产品 Owner'],['负责期','2024.10—2025.02'],['数据观察','截至 2025.08'],['项目类型','增长机制 / 转化体验']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / THE OPPORTUNITY</p><h3>用户需要一个“可以先试试看”的入口。</h3><p>新用户在理解交易规则、判断风险和决定是否入金时会遇到连续门槛。项目以模拟体验作为低压力的第一步，再用任务和返现机制承接后续行为。我的责任是从目标和规则出发，把体验路径做成团队能理解、能交付、能观察的完整产品机制。</p><div class="case-callout"><span>PRODUCT QUESTION</span><b>怎样让用户从“看懂产品”，走到“愿意尝试”，再走到“完成真实交易”？</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / USER JOURNEY</p><h3>把增长路径拆成六个可观察的关键节点。</h3><div class="journey"><div><i>01</i><b>发现入口</b><small>知道可以先模拟体验</small></div><div><i>02</i><b>理解规则</b><small>明确体验与任务条件</small></div><div><i>03</i><b>开始模拟</b><small>在低风险环境中尝试</small></div><div><i>04</i><b>完成任务</b><small>将体验转成进度反馈</small></div><div><i>05</i><b>领取奖励</b><small>确认阶段性完成结果</small></div><div><i>06</i><b>真实交易</b><small>承接首入金行为</small></div></div><div class="case-note">流程是对原稿策略图、模拟体验及任务中心页面的归纳；完整状态和规则以原始项目材料为准。</div></section>
      <section class="case-section"><p class="eyebrow">03 / INTERACTION LOGIC</p><h3>前台任务进度，和后台规则配置需要对得上。</h3><div class="logic-grid"><article><span>用户侧</span><h4>入口 → 参与 → 反馈</h4><p>让用户知道如何开始模拟体验、任务做到哪一步，以及奖励是否可以领取。</p></article><article><span>机制侧</span><h4>条件 → 任务 → 奖励</h4><p>把活动要求拆成用户能理解的任务，与后台可配置的条件建立映射。</p></article><article><span>转化侧</span><h4>完成体验 → 下一步行动</h4><p>用行为漏斗观察用户从参与任务到领取奖励、完成首入金的变化。</p></article></div></section>
      <section class="case-section"><p class="eyebrow">04 / OWNER SCOPE</p><h3>独立 Owner 把增长目标落成跨团队可执行的产品机制。</h3><div class="owner-list"><div><b>目标与口径</b><p>梳理模拟体验与真实交易之间的转化目标，确定关键行为与观察口径。</p></div><div><b>机制与交互</b><p>将任务、奖励、入口和用户反馈拆成可沟通的产品规则与交互说明。</p></div><div><b>跨团队交付</b><p>对齐产品、运营和研发对前台体验与后台配置之间的理解。</p></div><div><b>后续观察</b><p>我负责至 2025.02；数据继续观察至 2025.08，分别呈现负责期与观察期。</p></div></div></section>
      <section class="case-section"><p class="eyebrow">05 / FUNNEL & RESULT</p><h3>从模拟参与到首入金，漏斗走到了哪里。</h3><div class="case-funnel"><div><b>≈200K</b><span>新用户样本</span></div><div><b>≈120K</b><span>KYC 未通过</span></div><div><b>≈17K</b><span>进入模拟体验</span></div><div><b>3,954</b><span>参与任务</span></div><div><b>851</b><span>领取奖励</span></div><div><b>190</b><span>首次入金</span></div></div><div class="case-stat-row"><div class="case-stat"><b>1,908 U</b><span>平均首入金</span></div><div class="case-stat"><b>57 U</b><span>体验成本口径</span></div><div class="case-stat"><b>≈33×</b><span>首入金 / 体验成本比</span></div></div><div class="case-note">约 33× 是平均首入金金额与体验成本的比值，不代表利润、净回收或获客 ROI；负责期与观察期分开。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL CASE / FULL MATERIALS</p><h3>分别查看返现独立项目集和总集里的原始流程稿。</h3><div class="source-grid">${sourceLink('cashback','模拟返现｜独立案例全稿','24 页 · 策略、数据与复盘')}${sourceLink('btcc','BTCC 模拟体验｜原版流程稿','总集第 81–88 页 · 策略、任务与交互')}</div></section>
      <div class="case-end"><span>MAXIN / CORE CASE 03</span><span>OWNER 2024.10—2025.02 · DATA THROUGH 2025.08</span></div>`
  },
  contract:{
    label:'TRADING SYSTEMS / ORDER EXECUTION / APP',
    title:'合约交易页交互优化',
    deck:'把合约交易页里的切换、参数输入和风险状态拆清楚，让用户在下单上下文里知道自己正在设置什么。',
    meta:[['原方案','合约交易主流程优化'],['版本记录','v8.7.5 · App'],['依据','16 条交互说明 / 多状态示意'],['关注点','下单效率 / 状态可见 / 操作边界']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / WHY ORDER ENTRY NEEDS CLARITY</p><h3>下单字段之间有依赖；状态不清会放大误操作风险。</h3><p>原方案检查从行情进入交易、现货 / 合约切换、开平仓、订单参数输入到委托确认等路径。风险集中在多次切换、输入与滑杆相互覆盖、杠杆状态不适用但仍可操作，以及用户看不清交易额和可用余额的变化。</p><div class="case-callout"><span>PRODUCT PRINCIPLE</span><b>把关键参数放在同一上下文解释；当条件不允许操作时，状态和原因也必须可见。</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / ORDER JOURNEY</p><h3>从行情进入订单，把输入、预估与确认连成一条路径。</h3><div class="journey"><div><i>01</i><b>进入交易</b><small>行情页直达下单</small></div><div><i>02</i><b>选择交易模式</b><small>合约 / 现货状态明确</small></div><div><i>03</i><b>设定参数</b><small>杠杆、价格、数量</small></div><div><i>04</i><b>检查可用额</b><small>交易额和余额反馈</small></div><div><i>05</i><b>提交委托</b><small>超额时按输入方式进入相应处理</small></div><div><i>06</i><b>返回交易现场</b><small>确认委托与当前状态</small></div></div></section>
      <section class="case-section"><p class="eyebrow">03 / INTERACTION SPEC</p><h3>把原稿中的关键状态规则提炼为可执行的设计说明。</h3><div class="decision-table"><div class="decision-head"><span>交互点</span><span>原方案规则</span><span>要解决的问题</span></div><div><b>行情 / 交易入口</b><span>行情页主按钮改为直达交易；合约页增加现货切换入口</span><span>缩短路径，降低模式切换成本</span></div><div><b>杠杆滑杆</b><span>以倍数显示，最小步进 5×；存在挂单时锁定，不允许误调</span><span>减少对比例的误读，并说明不可操作状态</span></div><div><b>数量输入与滑杆</b><span>滑杆最小步进 1%；输入、拖动相互同步，避免清空已输数值</span><span>减少重复输入及控件冲突</span></div><div><b>价格与合约价值</b><span>限价单预填市场均价且可编辑；合约价值按输入状态显示，闲置后收起</span><span>保留关键反馈，控制信息噪声</span></div><div><b>交易额不足 / 超额</b><span>按余额与最小交易额区分提示；超额后按输入方式进入对应处理，并统一触发充值逻辑</span><span>让用户知道是调整数量、补充余额还是继续完成委托</span></div></div></section>
      <section class="case-section"><p class="eyebrow">04 / EVIDENCE & SCOPE</p><h3>方案完整记录了操作路径、异常状态和控件边界。</h3><div class="case-stat-row"><div class="case-stat"><b>16</b><span>条交互说明</span></div><div class="case-stat"><b>5×</b><span>杠杆滑杆最小步进</span></div><div class="case-stat"><b>1%</b><span>数量滑杆最小步进</span></div></div><div class="case-note">原稿为 v8.7.5 App 端主流程优化页，包含限价 / 市价、可用余额、数量边界、超额挂单及返回确认等状态。所提供材料未给出上线后的转化或误操作率数据；此案例只呈现有原稿支撑的方案与交互规则。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL PLAN / CONTRACT FLOW</p><h3>打开合约交易页优化方案原版。</h3><p>原稿是一张纵向长页，内含交易主流程截图与逐点交互说明。阅读器可滚动缩放；如果浏览器缩放不便，可下载原页 PDF 后放大查看。</p><div class="source-grid">${sourceLink('contract','合约交易优化｜方案细节','原作品集第 89 页 · App 主流程与交互说明')}${sourceLink('tp-sl','继续查看止盈止损公式方案','原作品集第 90 页 · 独立方案页')}</div></section>
      <div class="case-end"><span>MAXIN / SYSTEM CASE 04</span><span>CONTRACT ORDER FLOW / APP</span></div>`
  },
  risk:{
    label:'TRADING SYSTEMS / RISK EXPERIENCE / TP · SL',
    title:'止盈止损公式优化',
    deck:'重新审视触发价参考逻辑，让止盈止损结果与最新市场价格联动，并在多空场景下保持一致、可解释。',
    meta:[['原方案','止盈止损涨跌幅公式优化'],['版本记录','v8.8.7 · App'],['依据','问卷 / 行业对照 / 多空场景表'],['核心变化','开仓价参考 → 最新价参考']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / THE RISK</p><h3>快速波动与低流动性，会让“设好的止损”看起来失准。</h3><p>原方案记录的起因包括：低市值币种快速波动时，止盈止损可能频繁触发；低成交量下滑点造成实际盈亏与预估结果偏差；当参考价格口径不清时，用户难以判断触发价为何变化。原稿还引用问卷结论：超过 50% 的核心用户曾在交易中使用止盈止损。</p><div class="case-callout"><span>RISK UX QUESTION</span><b>触发价依据什么变化？当前价格和目标盈亏之间的关系，用户能否提前看懂？</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / PRICE LOGIC</p><h3>由固定开仓价参考，调整为跟随最新价格动态计算。</h3><div class="price-shift"><div><span>旧逻辑</span><b>开仓价</b><small>静态参考 · 与市场当前价可能脱节</small></div><i>→</i><div class="price-new"><span>新逻辑</span><b>最新价</b><small>动态联动 · 触发目标随最新价格更新</small></div></div><div class="case-note">原方案对比表将多头止盈、多头止损、空头止盈、空头止损四类场景逐一列出，说明由开仓价改为最新价后，触发价与盈亏目标如何联动。</div></section>
      <section class="case-section"><p class="eyebrow">03 / FOUR SCENARIOS</p><h3>方向不同，计算关系也要保持可解释。</h3><div class="scenario-grid"><article><span>LONG / PROFIT</span><b>多头止盈</b><small>价格上行到目标时触发</small></article><article><span>LONG / LOSS</span><b>多头止损</b><small>价格下行到风险边界时触发</small></article><article><span>SHORT / PROFIT</span><b>空头止盈</b><small>价格下行到目标时触发</small></article><article><span>SHORT / LOSS</span><b>空头止损</b><small>价格上行到风险边界时触发</small></article></div></section>
      <section class="case-section"><p class="eyebrow">04 / INTERACTION & SAFETY</p><h3>让输入、触发依据和预计结果一起被理解。</h3><div class="flow-board"><div class="flow-row"><span>SET</span><div><b>选择持仓方向</b><i>→</i><b>设置止盈 / 止损</b><i>→</i><b>选择触发参考</b></div></div><div class="flow-row"><span>CHECK</span><div><b>查看触发价格</b><i>→</i><b>核对预估盈亏</b><i>→</i><b>确认设置</b></div></div></div><p>原方案对 OKX、Bybit、Binance、Bitget 的触发价描述和最新价口径做了比较，并讨论触发方式标签、提示文案和滑杆交互；目标是在不同市场环境下让触发规则更清楚，减少用户对盈亏结果的误判。</p></section>
      <section class="case-section"><p class="eyebrow">05 / WHAT THE SOURCE PROVES</p><h3>原稿有明确的产品依据和方案版本记录。</h3><div class="case-stat-row"><div class="case-stat"><b>50%+</b><span>原问卷记录的止盈止损使用比例</span></div><div class="case-stat"><b>4</b><span>多空止盈 / 止损场景</span></div><div class="case-stat"><b>v8.8.7</b><span>App 方案版本记录</span></div></div><div class="case-note">现有方案材料包含问卷摘要、竞品对照、公式变化和交互示意，但未包含上线后影响指标。本页不把方案预期写成已验证结果。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL PLAN / FORMULA DETAIL</p><h3>打开止盈止损公式优化的原版方案细节。</h3><p>单独跳转到原总集对应方案页，包含行业对照、旧 / 新逻辑表格、四类持仓场景及交互标注；阅读器可缩放或下载查看。</p><div class="source-grid">${sourceLink('tp-sl','止盈止损公式优化｜原版方案','原作品集第 90 页 · 对照表与交互示意')}${sourceLink('contract','合约交易交互｜上下文方案','原作品集第 89 页 · 交易与触发流程')}</div></section>
      <div class="case-end"><span>MAXIN / SYSTEM CASE 05</span><span>RISK UX / TP · SL LOGIC</span></div>`
  }
};

const caseDialog=document.querySelector('#caseDialog');
const caseContent=document.querySelector('#caseContent');
const lightbox=document.querySelector('#lightbox');
const lightboxImage=document.querySelector('#lightboxImage');
function openCase(key){const item=caseData[key];if(!item)return;caseContent.innerHTML=`<header class="case-hero"><p class="eyebrow">${item.label}</p><h2>${item.title}</h2><p>${item.deck}</p><div class="case-meta">${item.meta.map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('')}</div></header><div class="case-body">${item.content}</div>`;caseContent.scrollTop=0;caseDialog.showModal();document.body.classList.add('modal-open')}
document.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>openCase(card.dataset.case)));
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===button));const filter=button.dataset.filter;document.querySelectorAll('.project-card').forEach(card=>{card.hidden=filter!=='all'&&!card.dataset.category.split(' ').includes(filter)})}));
document.querySelector('.dialog-close').addEventListener('click',()=>caseDialog.close());caseDialog.addEventListener('click',event=>{if(event.target===caseDialog)caseDialog.close()});caseDialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
function showImage(src,alt){lightboxImage.src=src;lightboxImage.alt=alt||'放大的产品界面截图';lightbox.showModal()}document.addEventListener('click',event=>{const target=event.target.closest('.zoomable');if(!target)return;const src=target.dataset.image||target.getAttribute('data-image');const image=target.tagName==='IMG'?target:target.querySelector('img');if(src)showImage(src,image?.alt)});
document.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',event=>{if(event.target===lightbox)lightbox.close()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.project-card,.about-head,.about-side,.contact').forEach(el=>{el.classList.add('reveal');observer.observe(el)});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&lightbox.open)lightbox.close()});
