const sourceLink=(doc,label,detail)=>`<a class="source-card" href="originals.html?doc=${doc}" target="_blank" rel="noopener"><span class="source-icon">↗</span><span><b>${label}</b><small>${detail}</small></span><span class="source-arrow">查看原稿</span></a>`;

const caseData={
  vip:{
    label:'MEMBERSHIP EXPERIENCE / VIP FEATURE OPTIMIZATION',
    title:'VIP 功能专项重构',
    deck:'围绕“看懂权益—判断升级—领取奖励—完成充值”重组 VIP 体验，把会员信息从说明页变成可行动的产品路径。',
    meta:[['项目','VIP 功能页数据体验提升专项'],['工作重点','用户研究 / 体验策略 / 交互方案'],['原稿范围','总集第 3–19 页'],['结果','3 项转化指标均有提升']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / CONTEXT</p><h3>用户看得到 VIP，却不一定知道如何参与和升级。</h3><p>原方案指出，用户对 VIP 升级条件、权益内容和参与路径的理解有门槛；新用户容易卡在“是否加入、如何加入”，老用户则更关心每日领奖、当前特权和距离下一等级还有多远。权益说明与行动入口之间存在断点，信息越多不等于体验越清楚。</p><div class="case-callout"><span>PRODUCT GOAL</span><b>提升 VIP 权益使用率，同时让充值与投资转化路径更顺。</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / RESEARCH → DESIGN</p><h3>先围绕用户任务分层，再决定信息和入口的优先级。</h3><div class="logic-grid"><article><span>新用户</span><h4>先理解，再加入</h4><p>识别 VIP 价值与升级条件；需要明确等级规则和加入方式，避免读完说明仍不知道下一步。</p></article><article><span>活跃老用户</span><h4>先行动，再比较</h4><p>每日领取奖励、查看当前权益和升级差距是高频任务，入口需要直接、状态需要清楚。</p></article><article><span>对比型用户</span><h4>深入查看，按需展开</h4><p>需要完整等级权益、奖励构成和历史信息；低频细节放进可展开的详情层，避免主页面拥挤。</p></article></div><p>研究结论指出：除奖励比例外，用户更在意功能是否易用、规则是否容易理解；在产品早期，易用性是辅助用户做出决策的基础。</p></section>
      <section class="case-section"><p class="eyebrow">03 / USER FLOW</p><h3>新用户和老用户，从同一会员入口进入不同的高优先级任务。</h3><div class="flow-board"><div class="flow-row"><span>NEW MEMBER</span><div><b>VIP 入口</b><i>→</i><b>理解权益 / 条件</b><i>→</i><b>加入或升级</b><i>→</i><b>前往充值</b></div></div><div class="flow-row"><span>RETURNING</span><div><b>VIP 入口</b><i>→</i><b>查看当前等级</b><i>→</i><b>领取每日奖励</b></div></div><div class="flow-row"><span>COMPARE</span><div><b>当前权益</b><i>→</i><b>等级对比</b><i>→</i><b>奖励构成 / 明细</b></div></div></div></section>
      <section class="case-section"><p class="eyebrow">04 / INTERACTION DECISIONS</p><h3>缩短高频路径，低频信息保留深度。</h3><div class="decision-table"><div class="decision-head"><span>场景</span><span>交互处理</span><span>设计理由</span></div><div><b>首次了解 VIP</b><span>突出加入 / 充值主入口，减少跨页找路径</span><span>让理解能够直接接到转化动作</span></div><div><b>每日回访用户</b><span>把“领取奖励”作为清晰的快速动作</span><span>匹配高频任务，避免每次重新找入口</span></div><div><b>查看等级特权</b><span>分层展示权益与升级条件，支持展开查看</span><span>兼顾快速浏览和完整比较</span></div><div><b>查看奖励流水</b><span>展示来源、日期与构成明细</span><span>改善奖励透明度，帮助用户规划充值收益</span></div></div><div class="case-note">交互决策来自原项目页：重点区分新 / 老用户任务、权益详情层级及奖励构成明细。</div></section>
      <section class="case-section"><p class="eyebrow">05 / MEASURED RESULTS</p><h3>体验调整之后，权益使用、充值和投资转化都有提升。</h3><div class="before-after-grid"><article><span>VIP 使用率 · 领取奖励</span><div><b>3.28%</b><i>→</i><strong>17.01%</strong></div><small>+13.73 个百分点</small></article><article><span>充值转化率</span><div><b>11.74%</b><i>→</i><strong>12.98%</strong></div><small>+1.24 个百分点</small></article><article><span>投资转化率</span><div><b>13.62%</b><i>→</i><strong>16.73%</strong></div><small>+3.11 个百分点</small></article></div><div class="case-note">以上为原作品集“效果验证”页所列测前 / 测后数据。原页未标注样本量和测试时间窗口，故不补充统计口径。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL CASE / 17 PAGES</p><h3>打开 VIP 原版方案，逐页查看研究、路径与界面。</h3><p>原始章节单独成页打开，保留原版布局和截图；页面内可缩放、滚动，也可下载这 17 页对应章节。</p><div class="source-grid">${sourceLink('vip','VIP 功能页体验提升｜原版全稿','总集第 3–19 页 · 含测前测后数据')}</div></section>
      <div class="case-end"><span>MAXIN / CORE CASE 01</span><span>VIP EXPERIENCE / MEASURED OUTCOME</span></div>`
  },
  voc:{
    label:'VOC EXPERIENCE INSIGHT / VOICECHANGER',
    title:'海外个消软件 VOC 洞察分析报告',
    deck:'以 VOC 体验报告和竞品分析为起点，梳理语音产品的发现、选择和调节体验，将分散问题落到核心使用流程。',
    meta:[['项目','VOC 体验洞察 / VoiceChanger'],['工作方法','VOC 报告 / 竞品分析 / 优化方案'],['问题规模','23+ 项问题 · 4 条核心流程'],['结果','上线后日付费率环比 +49.63%']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / WHY THIS PROJECT</p><h3>声音内容很多，但用户不容易找到合适的声音并顺利用起来。</h3><p>原案例从 VOC 体验报告和竞品分析出发，检查实时变声主页面、声音分类、筛选、收藏与参数调节等关键触点。核心体验挑战集中在内容发现效率、分类理解和控制项辨识：入口层级混杂，用户需要额外翻找；相近的调节描述增加理解负担；Pro 标识和定制内容容易让用户把功能限制理解成付费诱导。</p></section>
      <section class="case-section"><p class="eyebrow">02 / VOC → EXPERIENCE FLOW</p><h3>把“找到声音”到“完成变声”的连续任务串起来。</h3><div class="journey"><div><i>01</i><b>进入实时变声</b><small>识别主要功能入口</small></div><div><i>02</i><b>浏览声音库</b><small>按主题 / 类型快速筛选</small></div><div><i>03</i><b>选择并预览</b><small>理解效果，减少反复试错</small></div><div><i>04</i><b>调整参数</b><small>区分可调项与当前状态</small></div><div><i>05</i><b>收藏 / 使用</b><small>方便回访常用声音</small></div><div><i>06</i><b>继续探索</b><small>明确免费与付费内容边界</small></div></div></section>
      <section class="case-section"><p class="eyebrow">03 / FROM FEEDBACK TO DESIGN</p><h3>用信息组织和状态表达，减少搜索与理解成本。</h3><div class="decision-table"><div class="decision-head"><span>观察到的阻力</span><span>方案方向</span><span>用户收益</span></div><div><b>分类与筛选入口层级混杂</b><span>重组声音分类与筛选层级，突出常用类别</span><span>更快找到目标内容，降低浏览成本</span></div><div><b>主页面内容多，付费内容不易感知</b><span>调整内容呈现顺序与 Banner 位置</span><span>提升内容发现效率，明确可用内容</span></div><div><b>参数描述相近，状态反馈不清</b><span>区分调节项、默认值和已变更状态</span><span>减少多余思考与误操作</span></div><div><b>收藏与近期使用内容难回找</b><span>补充收藏 / 最近使用的快捷入口</span><span>缩短重复使用流程</span></div></div><div class="case-note">以上方案点据原 VOC 案例第 20–37 页归纳；其中页面现有问题清单至少列出 17 项具体问题，完整原稿中有逐项标注。</div></section>
      <section class="case-section"><p class="eyebrow">04 / CORE FLOWS</p><h3>把 23+ 项体验问题，收敛到 4 条核心流程。</h3><div class="flow-board"><div class="flow-row"><span>DISCOVER</span><div><b>主功能入口</b><i>→</i><b>分类 / 筛选</b><i>→</i><b>声音内容</b></div></div><div class="flow-row"><span>PREVIEW</span><div><b>选择声音</b><i>→</i><b>预览效果</b><i>→</i><b>调整参数</b></div></div><div class="flow-row"><span>RETURN</span><div><b>收藏 / 最近使用</b><i>→</i><b>快速回到常用内容</b></div></div></div></section>
      <section class="case-section"><p class="eyebrow">05 / MEASURED RESULT</p><h3>上线后，日付费率环比提升 49.63%。</h3><div class="result-hero"><b>+49.63%</b><span>VoiceChanger 日付费率<br>上线后环比提升 · 简历记录</span></div><div class="case-note">该结果来自简历项目描述。现有材料没有提供样本量、统计窗口和基线值；因此这里只按原口径呈现，不扩写归因或因果。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL CASE / 24 PAGES</p><h3>查看 VOC 原版体验分析与完整优化方案。</h3><p>对应总集第 20–43 页，包含产品背景、体验分析、问题归纳、用户旅程与多轮界面方案。结果数字另按简历记录标注。</p><div class="source-grid">${sourceLink('voc','VOC 体验洞察｜完整原版章节','总集第 20–43 页 · 24 页完整案例')}${sourceLink('voc-resume','VoiceChanger 结果口径｜简历记录','完整简历 PDF · 项目结果与任职记录')}</div></section>
      <div class="case-end"><span>MAXIN / CORE CASE 02</span><span>VOC INSIGHT / VOICECHANGER</span></div>`
  },
  cashback:{
    label:'BTCC / GROWTH EXPERIENCE / INDEPENDENT OWNER',
    title:'CEX 新用户孵化方案｜模拟返现',
    deck:'模拟返现不是一次性的活动页，而是把模拟体验、任务参与、奖励领取与真实交易连接起来的一段产品旅程。',
    meta:[['角色','独立产品 Owner'],['负责期','2024.10—2025.02'],['数据观察','截至 2025.08'],['项目类型','增长机制 / 转化体验']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / THE OPPORTUNITY</p><h3>用户需要一个“可以先试试看”的入口。</h3><p>新用户在理解交易规则、判断风险和决定是否入金时会遇到连续门槛。项目以模拟体验作为低压力的第一步，再用任务和返现机制承接后续行为。我的责任是从目标和规则出发，把体验路径做成团队能理解、能交付、能观察的完整产品机制。</p><div class="case-callout"><span>PRODUCT QUESTION</span><b>怎样让用户从“看懂产品”，走到“愿意尝试”，再走到“完成真实交易”？</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / USER JOURNEY</p><h3>把增长路径拆成六个可观察的关键节点。</h3><div class="journey"><div><i>01</i><b>发现入口</b><small>知道可以先模拟体验</small></div><div><i>02</i><b>理解规则</b><small>明确体验与任务条件</small></div><div><i>03</i><b>开始模拟</b><small>在低风险环境中尝试</small></div><div><i>04</i><b>完成任务</b><small>将体验转成进度反馈</small></div><div><i>05</i><b>领取奖励</b><small>确认阶段性完成结果</small></div><div><i>06</i><b>真实交易</b><small>承接首入金行为</small></div></div><div class="case-note">流程是对原稿策略图、模拟体验及任务中心页面的归纳；完整状态和规则以原始项目材料为准。</div></section>
      <section class="case-section"><p class="eyebrow">03 / INTERACTION LOGIC</p><h3>前台任务进度，和后台规则配置需要对得上。</h3><div class="logic-grid"><article><span>用户侧</span><h4>入口 → 参与 → 反馈</h4><p>让用户知道如何开始模拟体验、任务做到哪一步，以及奖励是否可以领取。</p></article><article><span>机制侧</span><h4>条件 → 任务 → 奖励</h4><p>把活动要求拆成用户能理解的任务，与后台可配置的条件建立映射。</p></article><article><span>转化侧</span><h4>完成体验 → 下一步行动</h4><p>用行为漏斗观察用户从参与任务到领取奖励、完成首入金的变化。</p></article></div></section>
      <section class="case-section"><p class="eyebrow">04 / OWNER SCOPE</p><h3>独立 Owner 把增长目标落成跨团队可执行的产品机制。</h3><div class="owner-list"><div><b>目标与口径</b><p>梳理模拟体验与真实交易之间的转化目标，确定关键行为与观察口径。</p></div><div><b>机制与交互</b><p>将任务、奖励、入口和用户反馈拆成可沟通的产品规则与交互说明。</p></div><div><b>跨团队交付</b><p>对齐产品、运营和研发对前台体验与后台配置之间的理解。</p></div><div><b>后续观察</b><p>我负责至 2025.02；数据继续观察至 2025.08，分别呈现负责期与观察期。</p></div></div></section>
      <section class="case-section"><p class="eyebrow">05 / FUNNEL & RESULT</p><h3>从模拟参与到首入金，漏斗走到了哪里。</h3><div class="case-funnel"><div><b>≈200K</b><span>新用户样本</span></div><div><b>≈120K</b><span>KYC 未通过</span></div><div><b>≈17K</b><span>进入模拟体验</span></div><div><b>3,954</b><span>参与任务</span></div><div><b>851</b><span>领取奖励</span></div><div><b>190</b><span>首次入金</span></div></div><div class="case-stat-row"><div class="case-stat"><b>1,908 U</b><span>平均首入金</span></div><div class="case-stat"><b>57 U</b><span>体验成本口径</span></div><div class="case-stat"><b>≈33×</b><span>首入金 / 体验成本比</span></div></div><div class="case-note">约 33× 是平均首入金金额与体验成本的比值，不代表利润、净回收或获客 ROI；负责期与观察期分开。</div></section>
      <section class="case-section"><p class="eyebrow">06 / BUSINESS SIGNALS · OBSERVED</p><h3>观察模拟体验之后，用户是否进入真实交易与持续行为。</h3><div class="case-stat-row cashback-outcomes"><div class="case-stat"><b>+38%</b><span>模拟用户真实交易转化提升</span></div><div class="case-stat"><b>&gt;20%</b><span>每日新增激活用户来自孵化池</span></div><div class="case-stat"><b>+22%</b><span>BTC / ETH 新手订单量增长</span></div><div class="case-stat"><b>11.11%</b><span>垂直转化用户出金 / 入金金额比<br>全局对照 65.3%</span></div></div><div class="evidence-line"><span class="evidence-label observed">OBSERVED · PROJECT / RESUME REPORTED</span><p>项目集与简历报告值，观察延续至 2025.08。现有材料未提供完整基线、去重口径、同期对照或统计显著性；这些是同周期业务信号，不能据此单独归因于方案。</p></div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL CASE / FULL MATERIALS</p><h3>分别查看返现独立项目集和总集里的原始流程稿。</h3><div class="source-grid">${sourceLink('cashback','模拟返现｜独立案例全稿','24 页 · 策略、数据与复盘')}${sourceLink('btcc','BTCC 模拟体验｜原版流程稿','总集第 81–88 页 · 策略、任务与交互')}</div></section>
      <div class="case-end"><span>MAXIN / CORE CASE 03</span><span>OWNER 2024.10—2025.02 · DATA THROUGH 2025.08</span></div>`
  },
  contract:{
    label:'TRADING SYSTEMS / ORDER EXECUTION / APP',
    title:'合约交易页交互优化',
    deck:'把合约交易页里的切换、参数输入和风险状态拆清楚，让用户在下单上下文里知道自己正在设置什么。',
    meta:[['原方案','合约交易主流程优化'],['版本记录','v8.7.5 · App'],['依据','16 条交互说明 / 多状态示意'],['关注点','下单效率 / 状态可见 / 操作边界']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / WHY ORDER ENTRY NEEDS CLARITY</p><h3>下单字段之间有依赖；状态不清会放大误操作风险。</h3><p>原方案检查从行情进入交易、现货 / 合约切换、开平仓、订单参数输入到委托确认等路径。风险集中在多次切换、输入与滑杆相互覆盖、杠杆状态不适用但仍可操作，以及用户看不清交易额和可用余额的变化。</p><div class="case-callout"><span>PRODUCT PRINCIPLE</span><b>把关键参数放在同一上下文解释；当条件不允许操作时，状态和原因也必须可见。</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / ORDER JOURNEY</p><h3>从行情进入订单，把输入、预估与确认连成一条路径。</h3><div class="journey"><div><i>01</i><b>进入交易</b><small>行情页直达下单</small></div><div><i>02</i><b>选择交易模式</b><small>合约 / 现货状态明确</small></div><div><i>03</i><b>设定参数</b><small>杠杆、价格、数量</small></div><div><i>04</i><b>检查可用额</b><small>交易额和余额反馈</small></div><div><i>05</i><b>提交委托</b><small>超额时按输入方式进入相应处理</small></div><div><i>06</i><b>返回交易现场</b><small>确认委托与当前状态</small></div></div></section>
      <section class="case-section"><p class="eyebrow">03 / INTERACTION SPEC</p><h3>把原稿中的关键状态规则提炼为可执行的设计说明。</h3><div class="decision-table"><div class="decision-head"><span>交互点</span><span>原方案规则</span><span>要解决的问题</span></div><div><b>行情 / 交易入口</b><span>行情页主按钮改为直达交易；合约页增加现货切换入口</span><span>缩短路径，降低模式切换成本</span></div><div><b>杠杆滑杆</b><span>以倍数显示，最小步进 5×；存在挂单时锁定，不允许误调</span><span>减少对比例的误读，并说明不可操作状态</span></div><div><b>数量输入与滑杆</b><span>滑杆最小步进 1%；输入、拖动相互同步，避免清空已输数值</span><span>减少重复输入及控件冲突</span></div><div><b>价格与合约价值</b><span>限价单预填市场均价且可编辑；合约价值按输入状态显示，闲置后收起</span><span>保留关键反馈，控制信息噪声</span></div><div><b>交易额不足 / 超额</b><span>按余额与最小交易额区分提示；超额后按输入方式进入对应处理，并统一触发充值逻辑</span><span>让用户知道是调整数量、补充余额还是继续完成委托</span></div></div></section>
      <section class="case-section"><p class="eyebrow">04 / EVIDENCE & SCOPE</p><h3>方案完整记录了操作路径、异常状态和控件边界。</h3><div class="case-stat-row"><div class="case-stat"><b>16</b><span>条交互说明</span></div><div class="case-stat"><b>5×</b><span>杠杆滑杆最小步进</span></div><div class="case-stat"><b>1%</b><span>数量滑杆最小步进</span></div></div><div class="case-note">原稿为 v8.7.5 App 端主流程优化页，包含限价 / 市价、可用余额、数量边界、超额挂单及返回确认等状态。所提供材料未给出上线后的转化或误操作率数据；此案例只呈现有原稿支撑的方案与交互规则。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL PLAN / CONTRACT FLOW</p><h3>打开合约交易页优化方案原版。</h3><p>原稿是一张纵向长页，内含交易主流程截图与逐点交互说明。阅读器可滚动缩放；如果浏览器缩放不便，可下载原页 PDF 后放大查看。</p><div class="source-grid">${sourceLink('contract','合约交易优化｜方案细节','原作品集第 89 页 · App 主流程与交互说明')}${sourceLink('tp-sl','继续查看止盈止损公式方案','原作品集第 90 页 · 独立方案页')}</div></section>
      <div class="case-end"><span>MAXIN / SYSTEM CASE 07</span><span>CONTRACT ORDER FLOW / APP</span></div>`
  },
  risk:{
    label:'TRADING SYSTEMS / RISK EXPERIENCE / TP · SL',
    title:'止盈止损公式优化',
    deck:'重新审视触发价参考逻辑，让止盈止损结果与最新市场价格联动，并在多空场景下保持一致、可解释。',
    meta:[['原方案','止盈止损涨跌幅公式优化'],['版本记录','v8.8.7 · App'],['依据','问卷 / 行业对照 / 多空场景表'],['核心变化','开仓价参考 → 最新价参考']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / THE RISK</p><h3>快速波动与低流动性，会让“设好的止损”看起来失准。</h3><p>原方案记录的起因包括：低市值币种快速波动时，止盈止损可能频繁触发；低成交量下滑点造成实际盈亏与预估结果偏差；当参考价格口径不清时，用户难以判断触发价为何变化。原稿还引用问卷结论：超过 50% 的核心用户曾在交易中使用止盈止损。</p><div class="case-callout"><span>RISK UX QUESTION</span><b>触发价依据什么变化？当前价格和目标盈亏之间的关系，用户能否提前看懂？</b></div></section>
      <section class="case-section"><p class="eyebrow">02 / PRICE LOGIC</p><h3>由固定开仓价参考，调整为跟随最新价格动态计算。</h3><div class="price-shift"><div><span>旧逻辑</span><b>开仓价</b><small>静态参考 · 与市场当前价可能脱节</small></div><i>→</i><div class="price-new"><span>新逻辑</span><b>最新价</b><small>动态联动 · 触发目标随最新价格更新</small></div></div><div class="case-note">原方案对比表将多头止盈、多头止损、空头止盈、空头止损四类场景逐一列出，说明由开仓价改为最新价后，触发价与盈亏目标如何联动。</div></section>
      <section class="case-section"><p class="eyebrow">03 / FOUR SCENARIOS</p><h3>方向不同，计算关系也要保持可解释。</h3><div class="scenario-grid"><article><span>LONG / PROFIT</span><b>多头止盈</b><small>价格上行到目标时触发</small></article><article><span>LONG / LOSS</span><b>多头止损</b><small>价格下行到风险边界时触发</small></article><article><span>SHORT / PROFIT</span><b>空头止盈</b><small>价格下行到目标时触发</small></article><article><span>SHORT / LOSS</span><b>空头止损</b><small>价格上行到风险边界时触发</small></article></div></section>
      <section class="case-section"><p class="eyebrow">04 / INTERACTION & SAFETY</p><h3>让输入、触发依据和预计结果一起被理解。</h3><div class="flow-board"><div class="flow-row"><span>SET</span><div><b>选择持仓方向</b><i>→</i><b>设置止盈 / 止损</b><i>→</i><b>选择触发参考</b></div></div><div class="flow-row"><span>CHECK</span><div><b>查看触发价格</b><i>→</i><b>核对预估盈亏</b><i>→</i><b>确认设置</b></div></div></div><p>原方案对 OKX、Bybit、Binance、Bitget 的触发价描述和最新价口径做了比较，并讨论触发方式标签、提示文案和滑杆交互；目标是在不同市场环境下让触发规则更清楚，减少用户对盈亏结果的误判。</p></section>
      <section class="case-section"><p class="eyebrow">05 / WHAT THE SOURCE PROVES</p><h3>原稿有明确的产品依据和方案版本记录。</h3><div class="case-stat-row"><div class="case-stat"><b>50%+</b><span>原问卷记录的止盈止损使用比例</span></div><div class="case-stat"><b>4</b><span>多空止盈 / 止损场景</span></div><div class="case-stat"><b>v8.8.7</b><span>App 方案版本记录</span></div></div><div class="case-note">现有方案材料包含问卷摘要、竞品对照、公式变化和交互示意，但未包含上线后影响指标。本页不把方案预期写成已验证结果。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL PLAN / FORMULA DETAIL</p><h3>打开止盈止损公式优化的原版方案细节。</h3><p>单独跳转到原总集对应方案页，包含行业对照、旧 / 新逻辑表格、四类持仓场景及交互标注；阅读器可缩放或下载查看。</p><div class="source-grid">${sourceLink('tp-sl','止盈止损公式优化｜原版方案','原作品集第 90 页 · 对照表与交互示意')}${sourceLink('contract','合约交易交互｜上下文方案','原作品集第 89 页 · 交易与触发流程')}</div></section>
      <div class="case-end"><span>MAXIN / SYSTEM CASE 08</span><span>RISK UX / TP · SL LOGIC</span></div>`
  },
  muse:{
    label:'C-END PRODUCT / 0→1 / STRUCTURE OPTIMIZATION',
    title:'Muse v1.0 PC 端产品结构与信息架构',
    deck:'从官网、品牌网站和游戏主页的组合出发，梳理 PC 用户任务与内容层级；用研究、原型和协作把 0→1 结构推进到上线。',
    meta:[['角色','主交互设计师'],['项目期','2023.04—2023.06'],['研究输入','目标用户调研 / 可用性测试 / 焦点小组'],['结果','项目上线 · 未提供量化结果']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / CONTEXT & PROBLEM</p><h3>多端扩展带来一个产品结构问题：PC 用户该如何理解并进入不同体验？</h3><p>简历记录的项目目标是适配多端用户、丰富使用场景，并根据 PC 用户操作习惯重梳产品和信息结构。原材料没有留下可公开的具体用户原话、问题频次或基线数据，因此这里描述项目命题，不把推导出的痛点写成研究结论。</p></section>
      <section class="case-section"><p class="eyebrow">02 / RESEARCH → INSIGHT</p><h3>先让方向在目标用户与团队讨论中接受检验。</h3><div class="logic-grid"><article><span>USER INPUT</span><h4>目标用户调研</h4><p>对多款 Demo 进行目标人群调研和可用性测试；简历未注明参与人数和招募口径。</p></article><article><span>QUALITATIVE</span><h4>焦点小组</h4><p>与部门同事开展定性讨论，收集对结构和方案的反馈；未把同事讨论等同于外部用户访谈。</p></article><article><span>COMPETITIVE</span><h4>竞品结构分析</h4><p>对照 5 款主流竞品的产品结构；简历未说明“三重结构”的具体维度。</p></article></div><div class="case-note">可确认的研究活动来自简历记录。具体用户洞察、样本规模和研究报告没有附在当前项目集中。</div></section>
      <section class="case-section"><p class="eyebrow">03 / JOURNEY & INFORMATION ARCHITECTURE</p><h3>围绕三个产品表面拆清入口、内容和后续任务。</h3><div class="journey"><div><i>SURFACE</i><b>官网</b><small>项目结构记录的产品入口之一</small></div><div><i>SURFACE</i><b>品牌网站</b><small>以品牌信息承接用户理解</small></div><div><i>SURFACE</i><b>游戏主页</b><small>连接用户对具体产品的探索</small></div><div><i>DELIVERY</i><b>公共提示</b><small>整理共用提示场景与组件规范</small></div></div><div class="case-note">此图按简历中的产品范围和职责重绘，表达项目结构的分工；它不是原始 Sitemap，也不代表已验证的用户路径。</div></section>
      <section class="case-section"><p class="eyebrow">04 / PRODUCT & DELIVERY</p><h3>用 Demo、结构方案和交付规范把体验判断转成团队可执行内容。</h3><div class="decision-table"><div class="decision-head"><span>决策对象</span><span>本人工作</span><span>可追溯交付</span></div><div><b>PC 产品结构</b><span>按 PC 操作习惯重梳功能与内容结构</span><span>产品结构、信息结构与操作流程方案</span></div><div><b>多页面体验</b><span>覆盖官网、品牌网站与游戏主页</span><span>多个 Demo 与页面需求规格</span></div><div><b>设计实现</b><span>与 UI、研发协作，确认可实现边界、接口和公共组件</span><span>组件应用规范、PRD、研发跟进与验收</span></div></div></section>
      <section class="case-section"><p class="eyebrow">05 / OUTCOME & NEXT VALIDATION</p><h3>项目成功上线；现有材料没有量化上线效果。</h3><div class="evidence-line"><span class="evidence-label observed">OBSERVED · 项目记录</span><p>简历记录项目上线，以及本人负责从 0 到 1 的产品结构、信息结构、用户路径和交互流程规划。未提供上线后任务成功率、跳出率或用户满意度。</p></div><div class="evidence-line"><span class="evidence-label framework">FRAMEWORK · 建议验证</span><p>按新用户首次到达、理解产品、进入具体主页等任务，测任务成功率、误入路径、完成时长和可用性反馈；在补齐方案与样本后再比较版本。</p></div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL SOURCE</p><h3>查看简历中的项目原始记录。</h3><div class="source-grid">${sourceLink('muse-resume','Muse v1.0｜简历原始项目记录','完整简历 PDF · 项目职责与交付')}</div></section>
      <div class="case-end"><span>MAXIN / SELECTED CASE 01</span><span>MUSE v1.0 / PC PRODUCT</span></div>`
  },
  research:{
    label:'USER RESEARCH / FEEDBACK OPERATING MODEL',
    title:'用户研究机制建设与数据支持',
    deck:'让分散的用户声音和行为数据进入产品决策：建立定期调研、阶段转化分析与策略回看的协作机制。',
    meta:[['角色','用户研究协同负责人'],['项目期','2025.01—2025.03'],['研究输入','KOL / 实际用户调研 / Spike 行为数据'],['已有记录','问卷回收逾 5,000 份 · 非去重用户数']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / WHY AN OPERATING MODEL</p><h3>单次调研难以持续回答：用户在哪个阶段受阻，下一版应该改什么？</h3><p>简历把这段工作定义为用户研究机制建设与数据支持落地：定期开展调研与转化行为分析，覆盖 KOL 和实际用户；配合产品、运营输出报告，为新手任务、返现等产品策略提供输入。</p></section>
      <section class="case-section"><p class="eyebrow">02 / RESEARCH LOOP</p><h3>把反馈、研究、行为证据和版本复盘放进同一条链路。</h3><div class="loop-card"><div><b>用户反馈 / 问卷</b><span>整理问题与人群阶段</span></div><i>→</i><div><b>用户研究</b><span>KOL 与实际用户调研</span></div><i>→</i><div><b>行为分析</b><span>结合 Spike 观察转化路径</span></div><i>→</i><div><b>产品决策</b><span>形成策略与版本输入</span></div><i>→</i><div><b>回看反馈</b><span>让下一轮研究有问题可追</span></div></div><div class="case-note">前四项工作方式见简历；“版本回看”作为本页建议的闭环步骤展示，不代表简历提供了每轮迭代的完整日志。</div></section>
      <section class="case-section"><p class="eyebrow">03 / PRODUCT IMPLICATION</p><h3>研究产出服务于具体策略选择，而不止于洞察归档。</h3><div class="decision-table"><div class="decision-head"><span>研究输入</span><span>判断方向</span><span>产品应用</span></div><div><b>不同阶段转化路径</b><span>识别新手关键行为和阻断环节</span><span>新手任务与分阶段引导</span></div><div><b>用户反馈与行为数据</b><span>对比表达意图与真实行为</span><span>模拟交易返现、转化奖励金及自动任务激励等策略的方向输入</span></div></div></section>
      <section class="case-section"><p class="eyebrow">04 / EVIDENCE & BOUNDARY</p><h3>可确认的是研究机制与回收规模，尚无可公开的研究质量指标。</h3><div class="result-hero"><b>5,000+</b><span>问卷回收量<br>来自简历记录；不是去重用户数</span></div><div class="case-note">现有材料未说明有效样本数、问卷题目、回收时间分布、用户访谈数量或由此减少的方向误判比例。这里不把“显著降低误判率”转换成未经提供的数字。</div></section>
      <section class="case-section"><p class="eyebrow">05 / VALIDATION FRAMEWORK</p><h3>下一步可用三类指标评估研究机制是否有效。</h3><div class="scenario-grid"><article><span>RESEARCH QUALITY</span><b>证据质量</b><small>有效回答率、样本覆盖、洞察可复核性</small></article><article><span>DECISION USE</span><b>决策采用</b><small>研究结论进入需求与版本的比例</small></article><article><span>PRODUCT EFFECT</span><b>产品变化</b><small>对应用户任务的完成率、流失与反馈趋势</small></article><article><span>FRAMEWORK ONLY</span><b>待建立基线</b><small>目前未提供上述指标的历史结果</small></article></div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL SOURCE</p><h3>查看简历中的机制建设原始记录。</h3><div class="source-grid">${sourceLink('research-resume','用户研究机制｜简历项目记录','完整简历 PDF · 用户研究协同负责人经历')}</div></section>
      <div class="case-end"><span>MAXIN / SELECTED CASE 04</span><span>USER RESEARCH OPERATING MODEL</span></div>`
  },
  cmb:{
    label:'FINANCIAL SERVICES / USER RESEARCH / EXPERIENCE CONSISTENCY',
    title:'招行 CMBSans 数字体与跨平台体验一致性',
    deck:'以数字字形的统一作为用户体验与品牌治理切口，连接问卷动机、字体规范、多平台应用和体验测试。',
    meta:[['角色','用户研究 / 产品交互'],['项目期','2021.03—2021.07'],['研究输入','用户问卷 · 简历记录样本 300'],['结果口径','结果摘自简历；原始研究报告未附']],
    content:`
      <section class="case-section"><p class="eyebrow">01 / CONTEXT</p><h3>不同产品各自采购和使用数字字体，增加了维护成本，也造成跨产品体验不一致。</h3><p>项目围绕招行数字字形的一致性展开。简历记录的业务侧动因包括字体授权成本、品牌延续和多产品应用；用户侧则关注页面美观、品牌一致、信任感和学习成本。</p></section>
      <section class="case-section"><p class="eyebrow">02 / USER RESEARCH</p><h3>问卷记录的首要诉求不只是“更好看”，也包括信任与易学。</h3><div class="motivation-bars"><div><span>页面整体美观</span><i><b style="width:34%"></b></i><strong>34%</strong></div><div><span>品牌一致性</span><i><b style="width:31%"></b></i><strong>31%</strong></div><div><span>系统信任感</span><i><b style="width:25%"></b></i><strong>25%</strong></div><div><span>降低学习成本</span><i><b style="width:10%"></b></i><strong>10%</strong></div></div><div class="case-note">问卷样本数 300、动机比例均见简历项目记录。未提供问卷原题、受访者构成和原始数据表，比例用于呈现简历记载，不扩展为总体用户结论。</div></section>
      <section class="case-section"><p class="eyebrow">03 / PRODUCT & DESIGN SYSTEM</p><h3>把用户诉求转成跨产品可复用的数字体验规范。</h3><div class="flow-board"><div class="flow-row"><span>RESEARCH</span><div><b>用户与业务动机</b><i>→</i><b>统一数字字形需求</b></div></div><div class="flow-row"><span>STRUCTURE</span><div><b>品牌特征提取</b><i>→</i><b>字形重绘与校准</b><i>→</i><b>规范化输出</b></div></div><div class="flow-row"><span>APPLICATION</span><div><b>零售 / 对公</b><i>→</i><b>多设备与多平台</b><i>→</i><b>多场景应用测试</b></div></div></div><p>简历列出的方案包括数字字形再创作、基线与切角校准、多平台兼容以及零售、对公、广告和运营环境的应用测试。</p></section>
      <section class="case-section"><p class="eyebrow">04 / OUTCOME · OBSERVED</p><h3>简历记录体验效率与品牌相关指标改善，但没有提供完整测量方案。</h3><div class="before-after-grid"><article><span>跨平台操作效率</span><div><strong>+6.2%</strong></div><small>简历记录 · 样本与窗口未提供</small></article><article><span>品牌辨识度</span><div><strong>+15%</strong></div><small>简历记录 · 归因边界未提供</small></article><article><span>系统信任度</span><div><strong>+10%</strong></div><small>简历记录 · 量表与窗口未提供</small></article></div><div class="evidence-line"><span class="evidence-label observed">OBSERVED · RESUME-REPORTED</span><p>以上是简历记载的结果，不表述为独立验证的因果提升。结果数值、统计窗口和测量工具待原始报告核对。</p></div></section>
      <section class="case-section"><p class="eyebrow">05 / NEXT VALIDATION</p><h3>把“体验一致”落到可复测的任务表现。</h3><div class="case-note">FRAMEWORK：可比较统一字体前后的数字辨识任务成功率、完成时长、跨产品切换错误和可读性评价；建议按零售、对公及设备环境分层。当前没有原始可用性测试结果可供呈现。</div></section>
      <section class="case-section"><p class="eyebrow">ORIGINAL SOURCE</p><h3>查看简历中的项目原始记录。</h3><div class="source-grid">${sourceLink('cmb-resume','CMBSans 数字体体验优化｜简历原始记录','完整简历 PDF · 招商银行项目经历')}</div></section>
      <div class="case-end"><span>MAXIN / SELECTED CASE 05</span><span>CMBSANS / EXPERIENCE CONSISTENCY</span></div>`
  }
};

const caseDialog=document.querySelector('#caseDialog');
const caseContent=document.querySelector('#caseContent');
const lightbox=document.querySelector('#lightbox');
const lightboxImage=document.querySelector('#lightboxImage');
const caseCredits={
  muse:{role:'主交互设计师',work:'规划产品结构、信息结构、用户路径和操作流程；制作 Demo，跟进 PRD、UI 与研发还原及验收。',partners:'UI 与研发；沟通接口、实现边界和公共组件规范。',boundary:'项目上线有简历记录；没有量化效果或原始研究报告。',status:'OBSERVED · 项目交付',source:'简历中的 Muse v1.0 项目记录。'},
  voc:{role:'交互设计师 / 体验优化方案牵头',work:'负责全局版本体验优化方案；结合 VOC、竞品与旅程分析梳理问题并提出解决方案。',partners:'简历未列明具体协作团队；不推断数据、运营或研发的个人职责。',boundary:'问题数与付费率来自作品集和简历记录；没有样本、窗口或对照组信息。',status:'OBSERVED · 项目 / 简历记录',source:'总集第 20–43 页及简历 VoiceChanger 项目记录。'},
  cashback:{role:'体验策略产品 Owner',work:'提出并设计模拟返现孵化机制，连接模拟体验、任务成长、奖励金与真实交易；明确负责期和后续观察期。',partners:'简历概述与客服、研发、运营的体验协作；该案例材料未逐项标出各方在本项目中的决策分工。',boundary:'负责至 2025.02，数据观察至 2025.08；源案例记录漏斗和后续用户结构，未提供随机对照实验。',status:'OBSERVED · 独立案例数据',source:'独立模拟返现项目集 24 页；简历项目记录。'},
  vip:{role:'交互设计师',work:'以定性分析、可用性测试和竞品方法定位问题；重梳框架、结构与交互方案。',partners:'简历提及向上下游岗位传达改版意图；未列出具体团队名和分工。',boundary:'前后数据见总集第 19 页；测试样本与时间窗口未提供，充值率简历与原页基线相差 0.01 个百分点。',status:'OBSERVED · 总集第 19 页',source:'VIP 原方案效果验证页；简历 MuseCasino VIP 项目记录。'},
  contract:{role:'交互方案贡献；具体责任范围未在简历中单列',work:'原方案记录订单路径、参数联动、状态和异常边界；本页只展示原稿可见的方案规则。',partners:'原稿未注明个人对接的具体岗位，不补写研发跟进或上线责任。',boundary:'材料可以证明交互说明和版本规则；未提供上线状态、效果数据或误操作率。',status:'SOURCE DETAIL · 原稿方案',source:'总集第 89 页，v8.7.5 App 合约交互方案。'},
  risk:{role:'交互方案贡献；具体责任范围未在简历中单列',work:'原方案对比止盈止损触发参考与多空场景，整理交互说明和提示方向。',partners:'原稿有竞品口径比较；未注明用户研究、数据或工程团队分工。',boundary:'问卷摘要称核心用户使用止盈止损超过 50%；无样本数、问卷方法或上线后结果。',status:'OBSERVED + SOURCE DETAIL',source:'总集第 90 页，止盈止损公式方案。'},
  research:{role:'用户研究协同负责人',work:'搭建定期用户调研和转化行为分析机制；按用户阶段分析路径，并配合输出研究报告。',partners:'与产品、运营同步研究报告；具体审批、研究招募和数据处理分工未展开。',boundary:'简历报告问卷回收逾 5,000 份；未注明去重用户量或有效样本口径。',status:'OBSERVED · 简历记录',source:'简历第 4–5 页，用户研究机制建设与数据支持。'},
  cmb:{role:'用户研究 / 产品交互',work:'参与问卷调研，并把品牌一致性、学习成本等用户诉求转成数字字体规范和多平台应用测试。',partners:'项目覆盖零售、对公及多平台应用；简历未列出具体协作岗位分工。',boundary:'样本数 300 与结果为简历记录；原始问卷、量表和测量窗口未提供。',status:'OBSERVED · 简历记录',source:'简历第 9–10 页，CMBSans 数字体项目。'}
};
function renderCaseCredits(key){const c=caseCredits[key];if(!c)return'';const type=c.status.startsWith('OBSERVED')?'observed':'verified';return `<section class="case-section case-credits"><p class="eyebrow">MY ROLE / COLLABORATION / EVIDENCE</p><div class="role-grid"><article><span>MY ROLE</span><h4>${c.role}</h4><p>${c.work}</p></article><article><span>CROSS-FUNCTIONAL COLLABORATION</span><h4>协作与决策边界</h4><p>${c.partners}</p></article><article><span>OUTCOME BOUNDARY</span><h4>个人贡献与团队结果分开</h4><p>${c.boundary}</p></article></div><div class="evidence-line"><span class="evidence-label ${type}">${c.status}</span><p>${c.source}</p></div></section>`}
function labelCaseEvidence(key){const labels={vip:['OBSERVED · SOURCE PRE / POST'],voc:['OBSERVED · RESUME-REPORTED'],cashback:['OBSERVED · PROJECT FUNNEL'],contract:['VERIFIED · SOURCE SPEC'],risk:['SOURCE DETAIL · REPORTED SURVEY'],cmb:['OBSERVED · RESUME-REPORTED'],research:['OBSERVED · RESUME-REPORTED']};const [text]=labels[key]||['SOURCE FACT'];caseContent.querySelectorAll('.before-after-grid,.result-hero,.case-funnel,.case-stat-row,.motivation-bars').forEach(block=>{if(block.previousElementSibling?.classList.contains('case-evidence-stamp'))return;const stamp=document.createElement('span');stamp.className='evidence-label '+(text.startsWith('OBSERVED')?'observed':'verified')+' case-evidence-stamp';stamp.textContent=text;block.before(stamp)})}
function openCase(key){const item=caseData[key];if(!item)return;caseContent.innerHTML=`<header class="case-hero"><p class="eyebrow">${item.label}</p><h2>${item.title}</h2><p>${item.deck}</p><div class="case-meta">${item.meta.map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('')}</div></header><div class="case-body">${renderCaseCredits(key)}${item.content}</div>`;labelCaseEvidence(key);caseContent.scrollTop=0;caseDialog.showModal();document.body.classList.add('modal-open')}
document.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>openCase(card.dataset.case)));
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===button));const filter=button.dataset.filter;document.querySelectorAll('.project-card').forEach(card=>{card.hidden=filter!=='all'&&!card.dataset.category.split(' ').includes(filter)})}));
document.querySelector('.dialog-close').addEventListener('click',()=>caseDialog.close());caseDialog.addEventListener('click',event=>{if(event.target===caseDialog)caseDialog.close()});caseDialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
function showImage(src,alt){lightboxImage.src=src;lightboxImage.alt=alt||'放大的产品界面截图';lightbox.showModal()}document.addEventListener('click',event=>{const target=event.target.closest('.zoomable');if(!target)return;const src=target.dataset.image||target.getAttribute('data-image');const image=target.tagName==='IMG'?target:target.querySelector('img');if(src)showImage(src,image?.alt)});
document.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',event=>{if(event.target===lightbox)lightbox.close()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.project-card,.about-head,.about-side,.contact').forEach(el=>{el.classList.add('reveal');observer.observe(el)});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&lightbox.open)lightbox.close()});

